# Generated by Django 5.1.3 on 2025-01-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht11',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
