# Generated by Django 5.1.3 on 2025-01-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_dht11_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dht11',
            name='resolved',
        ),
    ]
