# Generated by Django 5.1.3 on 2025-01-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_remove_dht11_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
